spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/gym_crm_prod
    username: prod_user
    password: prod_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
